### ISSUE TITLE
Visueller Hinweis dass Berechnung stattfindet

### ISSUE THREAD

**Issue by flaimo** [JOSM/areaselector#12]
Hallo,

wenn man auf ein Gebäude klickt, kann es manchmal bis zu 2,3 Sekunden dauern bis der Gebäudeumriss als Way dargestellt wird. Es wäre gut, wenn angezeigt werden würde, dass gerade eine Berechnung stattfindet. Es ist mir schon öfters passiert, dass ich dann noch ein weiteres Mal in einen Gebäudeumriss geklickt habe, weil ich dachte, die erste Eingabe wurde nicht erkannt, was darin resultierte, dass ich dann zwei Ways hatte.

**Comment by r00tat** [comment]
War nicht so erfolgreich bei der Implementierung, ist deswegen postponed.

https://github.com/JOSM/JOSM-areaselector/tree/progressdialog
