### ISSUE TITLE
Inappropriate source tag and procedure

### ISSUE THREAD

**Issue by a-pirard** [JOSM/areaselector#27]
Hi Paul,

Thanks again for fixing AT, and I'm glad to have been of some help.
I hope to come back soon with remarks and findings, but the following prevents my using it.

In the meantime, this is a remark from a compatriot Sus, she is not fluent with English and I interpret.
She regrets that the layers have to be turned off to be excluded from new feature SOURCE.
I myself evaluated it and found strange to use my shorthands for SOURCE, such as "BE SPW PIC0"
when the real value is  "20cm-near PICC http://geoportail.wallonie.be 2017".
Should I use this value as my shorthand, I would no longer make sense of them.

Moreover, I regret that AS overwrites any explicit SOURCE that the user sets, or selected with marvellous drop-down.

All in all,
Sus suggests, and I agree, that there should be a check box indicating if the SOURCE tag should be automatically filled or it it behaves like the other tags.
I suggest that the feature shouldn't overwrite a SOURCE value set by the user.
Note that an "Intentionally left blank" value producing no tag makes the check box unnecessary but is cryptic.

Please note that I updated my other "replacing a building" ticket which is important and seems easy to do, and that I added a BTW to it describing another useful feature.

TIA.

**Comment by r00tat** [comment]
Hi! 
I've found the source of the source tag issue ;) and implemented a fix for that. I'll publish a new version shortly.

The root cause of this behaviour was that the plugin always set the source from the layers in JOSM and then started the address dialog. The address dialog always respects existing values and therefore will only show the auto generated source and not the last value. This is now fixed.

**Comment by a-pirard** [comment]
On 2017-07-14 12:15, Paul wrote:
>
> Hi!
> I've found the source of the source tag issue ;) and implemented a fix
> for that. I'll publish a new version shortly.
>
> The root cause of this behaviour was that the plugin always set the
> source from the layers in JOSM and then started the address dialog.
> The address dialog always respects existing values and therefore will
> only show the auto generated source and not the last value. This is
> now fixed.
>
Hi Paul,
The fix looks like excellent.
I used SOURCE without problem now.
It's now possible to use AS normally again.
I'm warning my compatriots who complained.
Thanks!
