### ISSUE TITLE
building replacement does not override building=yes

### ISSUE THREAD

**Issue by a-pirard** [JOSM/areaselector#28]
I made a series of replacement of building=yes areas with building=house.
AS would repeatedly use building=yes instead.
Normally, the existing tags are overridden with AS'es new ones.
But should a building=hangar be encountered, the mapper must wonder which is right.
Replace Geometry has a tag conflict resolution for that.
Does that happen with any tag?

**Comment by r00tat** [comment]
Areaselector will use all tags from the old building and replace it with the values from the new one. As Areaselector tags all buildings automatically with building=yes this will lead to the building tag always be yes. 

I'll fix this, so the last used value will be used.
