### ISSUE TITLE
building replacement undo error

### ISSUE THREAD

**Issue by a-pirard** [JOSM/areaselector#29]
Hi Paul,

The attached file is the result of completely undoing the replacement of the upper right building with the bottom left one.
Trying to play with that construct produces program exceptions.
JOSM is in a funny state and must be restarted without risking to save anything, hence ruining work.

Hoping this will help.

André.

[AS undo failure.osm.zip](https://github.com/JOSM/areaselector/files/1160852/AS.undo.failure.osm.zip)

**Comment by r00tat** [comment]
This does not really help. If you can send me a stacktrace I can look into the details.

**Comment by a-pirard** [comment]
On 2017-07-28 11:29, Paul wrote:
>
> This does not really help. If you can send me a stacktrace I can look
> into the details.
>
No need to send you a stacktrace that you can produce yourself and that
will be useless when the original problem will be corrected.
Do exactly as I said:
Start JOSM. Download Object Way: 327747420. Open PICC imagery. Run AS
near that way. Undo several times.
Can't fully Undo, you'll see the funny picture I sent.
Only trying to delete or move what remains produces an exception.
While proofing this, replacement did not always work. Only at low zoom?
Only the first time? Only after moving original way? ...?
Does what I said help?

**Comment by a-pirard** [comment]
Paul,
This issue seems to be solved.
I see no more problems undoing what AS did.
But I'd better let you close the case yourself.
BTW: is it possible to be warned of AS updates and to see a log of the changes?
Often useful to coordinate our own tests and comments.
Thanks and best regards.

**Comment by r00tat** [comment]
Hi Andre,
Normally if I fix an issue I will refer to the issue in the commit, so you should see when an issue gets resolved. 
In this case something in JOSM might have changed, or one of the other contributers fixed it.

**Comment by a-pirard** [comment]
On 2018-05-08 18:03, Paul wrote:
> Normally if I fix an issue I will refer to the issue in the commit, so 
> you should see when an issue gets resolved.
Hi Paul,
I wasn't speaking of being notified that my issues are resolved.
I was speaking of being warned of any update and what they include.
It's great to notice improvements but it's making wrong conclusions 
about one's settings tuning if you don't know them.

I might try to run your image algorithms outside of JOSM, such as with 
GIMP scripts. Is it possible and realistic?
I stumbled upon this and I wondered if it could help you.
https://wiki.openstreetmap.org/wiki/User:Balrog/Aerial_Imagery/Rectification

Is it possible to send you private e-mail?

All the best,
André.
