### ISSUE TITLE
AS is an interesting plugin not only for buildings!

### ISSUE THREAD

**Issue by mbranco2** [JOSM/areaselector#40]
Thank you guys for this plugin, I think it could be very useful to speed up the mapping of several features, not only buildings.
I'm an UN mapper (UNGSC-mbranco2), working most in Somalia, and I tried to use AS with ponds, meadows/farmlands, scrubs... : results are very interesting (see pics below).
So my request is very simple: why not to put in AS settings the default tags to assign to the new feature, avoiding to set "building=yes" ?

Also, it seems to me that "angle tolerance" is the parameter which set the accuracy of interpolation: for this kind of features accuracy is not so useful, so I set it to a high value (60), but often at least a part of the way has many unnecessary nodes.

In any case, I congratulate and thank you!

![Areaselector1](https://user-images.githubusercontent.com/7782994/104128722-7dab9380-5369-11eb-8723-a061b6fb70fb.jpg)
![Areaselector2](https://user-images.githubusercontent.com/7782994/104128728-8308de00-5369-11eb-9cf3-68408a59c74a.jpg)
![Areaselector3](https://user-images.githubusercontent.com/7782994/104128732-8603ce80-5369-11eb-9b6e-c1f42522be42.jpg)

**Comment by miurahr** [comment]
Same opinion here that AS is useful for other area features. Good idea!

Can @mbranco2  list up useful presets for AS? It is useful AS has a preference/configuration to select a  preset.

- building:  building=yes [default]
- pond: natural=water
- farmland: landuse=farmland
- meadow: landuse=meadow

any others?

**Comment by mbranco2** [comment]
well, I used AS also for natural=scrub and natural=wood (or landuse=forest).
                                 
But I ask: should it be a too "rude" solution to set a text box (with "building=yes" as default), giving the ability to customize as you like, maybe setting several tags (separated by plus sign or semicolon) ?
For example for ponds I use: natural=water+water=pond+intermittent=yes , or for mosques I set: building=mosque+amenity=place_of_worship+religion=muslim
Obviously this is handy if you map (as I do) looking in the same area for one feature at a time, if you prefer to map all features all together, you can leave the "tag(s)" textbox empty, so you don't have to delete the default value each time.

:-)

**Comment by r00tat** [comment]
Cool to hear that other people find it useful! I haven't been actively improving this plugin, but some other users in the JOSM community did. Let's see if I manage to add another setting as your idea makes totally sense!

**Comment by NLthijs48** [comment]
I'm also looking into using this plugin for pieces of grass/forest, which works nicely already except for the tagging part. I already crudely added a checkbox in the preferences to disable the `building=yes` tag it adds by default, but that indeed means that you still need to press `F3` (open preset search), find the preset you want (probably just arrow down for the last used), press enter, and confirm the preset dialog. So I think there are options to improve that workflow.

I have a proposal for extending the settings dialog a bit to make it more usable for non-buildings. I would propose to replace all tagging related settings with a radio button selection with the following options:
1. **None**
    - Just selects the generated polygon
2. **Preset search dialog**
    - Shows the dialog as if you pressed `F3`
3. **Specific preset**
    - Enter the name of the preset here (like `Geography/Land use/Grass`), could be upgraded to a preset search field for easier selection in the future
    - Supports all built-in presets
    - Should support custom presets as well if I understand the code correctly (otherwise I'll look into supporting that)
4. **Address dialog**
    - The custom address dialog of this plugin, or could we use the standard `Annotation/Address` preset dialog instead? It looks like the standard address preset dialog is actually more feature rich than the custom one implemented in this plugin. Only missing the `building=yes` tag I believe.
    - If going for the built-in preset, maybe a checkbox/input to add a `building` tag to it as well (but a custom preset + option 3 could be used as well to achieve this)
    - It looks like the `use austria address helper` toggle only makes sense when this option is selected

I already wrote code to trigger all of these options, which works. If you agree with this idea I'll start implementing the UI and settings storage changes to support this, and send it as a pull request when ready.
